// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAekA8rw7KaQURd4GnvHfSx5MHsAjSPyjg',
    appId: '1:640443735978:web:de886b400f90f3d603d5d3',
    messagingSenderId: '640443735978',
    projectId: 'todo-app-a5ac1',
    authDomain: 'todo-app-a5ac1.firebaseapp.com',
    storageBucket: 'todo-app-a5ac1.appspot.com',
    measurementId: 'G-HGJ0T4P8E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8YMq_RzKds1hYPvBxXl5qcxgwcCGCbh0',
    appId: '1:640443735978:android:bffd75c13245020103d5d3',
    messagingSenderId: '640443735978',
    projectId: 'todo-app-a5ac1',
    storageBucket: 'todo-app-a5ac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWLvRxhnxvig01ydkxK1maM56Frb8Th1Y',
    appId: '1:640443735978:ios:15e7da36a02f692603d5d3',
    messagingSenderId: '640443735978',
    projectId: 'todo-app-a5ac1',
    storageBucket: 'todo-app-a5ac1.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

}